package com.atlassian.jira.cloud.jenkins.common.model;

/**
 * Combination of Client ID and Secret generated by creating an OAuth app
 * from Jira admin page
 */
public class AppCredential {

    private final String clientId;
    private final String clientSecret;

    public AppCredential(final String clientId, final String clientSecret) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
    }

    public String getClientId() {
        return clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }
}
